[settings]
env_file = ".env"
disable_backends = ["asdf", "spm", "vfox"]
disable_default_registry = true
not_found_auto_install = true
pin = true

[env]
_.python.venv = { path = "{{ env.HOME }}/.cache/mise/venv", create = true }
